#!usr/bin/env python

import numpy as np
import matplotlib.pyplot as plt
import scipy.special as sp
import mpmath as mp
import os
import glob, re
from configurations.physics_constants import ME, ALPHA, HBAR_C, E_HARTREE, AU, C


#### FORTRAN DATA EXTRACTION

def Fortran_data():
    """
    Exctracts the output data generated by RADIAL FORTRAN subroutine, and calculates the g component for comparison

    This is probably a temporary function purely for comparing data.

    Results
    -------
    g_func : ndarray
        Calculated upper wave function component for kappa = -1
    E_values : ndarray
        The total relativistic energies on which g_func was evaluated
    """
    directory = "out_fortran"
    P_values = []
    E_values = []

    pattern = os.path.join(directory, "cxem_*.out")
    R_value_fortran = None

    for filename in sorted(glob.glob(pattern)):
        E = None
        with open(filename, "r") as f:
            for line in f:
                if "Free state:" in line:
                    match = re.search(r"E=\s*([+-]?\d+\.\d+E[+-]\d+)", line)

                    if match:
                        E = float(match.group(1))

                parts = line.split()

                # Skip header/non-data lines
                if len(parts) != 3:
                    continue

                try:
                    R = float(parts[0])
                    P = float(parts[1])

                    # First nonzero R
                    if R != 0.0:
                        if R_value_fortran is None:
                            R_value_fortran = R
                        P_values.append(P)
                        E_values.append(E)
                        break

                except ValueError:
                    continue
    if R_value_fortran is None:
        raise RuntimeError("No matching radius extracted")

    P_values = np.array(P_values)
    E_values = np.array(E_values) * E_HARTREE/1e6

    print(f"R = {R_value_fortran}")
    print(f"R in a.u = {R_value_fortran/ AU}")
    print(f"E values = {E_values}")
    print(f"P(R) values = {P_values}")



    p = np.sqrt(E_values * (E_values + 2*C**2))/C
    total_E = E_values + ME
    g_func = np.sqrt((total_E + ME)/(2*total_E)) * P_values /(p * R_value_fortran/AU)

    plt.figure(figsize=(12,8))
    plt.plot(E_values, g_func)
    plt.xscale("log")
    plt.show()

    return g_func, E_values

def find_mesh_point_R_au(grid_points, rN):
    """
    Obtains the index and value of r_grid which match the nuclear radius or come closest to it.

    Parameters
    ----------
    grid_points : ndarray
        One dimensional ndarray of the radial grid
    rN : float
        Dimensionless nuclear radius defined as R = 1.2 * A^(1/3) / HBAR_C

    Returns
    -------
    idx_R : int
        Index point at which grid_points matches nuclear radius or comes closest to it
    grid_point_R_au : float
        Value of grid_points which matches the nuclear radius or comes closest to it
    """
    R_au = rN * HBAR_C * 1e-15 /AU
    idx_R = 0
    grid_point_R_au = 0
    for i in range(0,len(grid_points)-1):
        if grid_points[i] <= R_au  and grid_points[i+1] > R_au:
            grid_point_R_au = grid_points[i]
            idx_R = i
            print(f"closest mesh point to R_au = {R_au: .5g} is at i ={idx_R} w/ mesh point value ={grid_point_R_au: .5g}")
            break
    return idx_R, grid_point_R_au


def calc_g_and_f(Ee, Z, A, data):
    """
    Calculate the radial Dirac wavefunction components g with kappa = -1 and f with kappa = +1.

    The functions are computed from the radial wavefunction components
    P and Q following the conventions used in
    "Angular Distributions of Emitted Electrons in the Two-Neutrino
    ββ Decay" by Ovidiu.

    Parameters
    ----------
    Ee : ndarray
        Total relativsitc energy values.
    Z : int
        Atomic number.
    A : int
        Mass number.
    data : dict
        Dictionary containing the radial wavefunction data with keys:

        - "T" : kinetic energy mesh
        - "P_n" : upper radial wavefunction component
        - "Q_p" : lower radial wavefunction component
        - "idx_R" : index corresponding to the nuclear radius
        - "mesh_point_R_au" : nuclear radius mesh point in atomic units

    Returns
    -------
    g_n1 : ndarray
        Upper component of dirac wavefunction for kappa = -1
    f_p1 : ndarray
        Lower component of dirac wavefunction for kappa = +1
    """
    Ee = np.asarray(Ee, dtype = float)

    T_mesh = data["T"]
    P_n = data["P_n"]
    Q_p = data["Q_p"]
    idx_R = data["idx_R"]
    mesh_point_R_au = data["mesh_point_R_au"]


    T_MeV = T_mesh * E_HARTREE/1e6
    Ee = T_MeV + ME
    p_au = np.sqrt(T_mesh * (T_mesh + 2*C**2))/C


    g_n1 = np.sqrt((Ee + ME)/(2*Ee)) * P_n[:,idx_R] /(p_au * mesh_point_R_au)
    f_p1 = np.sqrt((Ee + ME)/(2*Ee)) * Q_p[:,idx_R] / (p_au * mesh_point_R_au)
    # g_n1 =  P_n[:,idx_R] #/(p_au * mesh_point_R_au)
    # f_p1 =  Q_p[:,idx_R] #/ (p_au * mesh_point_R_au)
    return g_n1, f_p1



def Fermi_numerical(Ee, Z, A, data):
    """
    Calculate the numerical Fermi function from Dirac radial wavefunctions.

    The Fermi function is computed from the radial Dirac components
    g and f evaluated at the nuclear radius,

        F(Z, Ee) = 2 * (g^2 + f^2) / (s + 1)

    where

        s = sqrt(1 - (ALPHA * Z)**2).

    Parameters
    ----------
    Ee : array_like
        Total relativistic electron energies in MeV.

    Z : int
        Atomic number.

    A : int
        Mass number.

    data : dict
        Dictionary containing the radial wavefunction data with keys:

        - "T" : kinetic energy mesh
        - "P_n" : upper radial wavefunction component
        - "Q_p" : lower radial wavefunction component
        - "idx_R" : index corresponding to the nuclear radius
        - "mesh_point_R_au" : nuclear radius mesh point in atomic units

    Returns
    -------
    ndarray
        Numerical Fermi function evaluated at Ee.
    """
    s = np.sqrt(1-(ALPHA * Z)**2)

    T = Ee - ME
    T_mesh = data["T"]
    T_MeV = T_mesh * E_HARTREE/1e6

    g, f = calc_g_and_f(Ee, Z, A, data)


    Fermi_vals = (g**2 + f**2)

    return 2/(s+1) * np.interp(T, T_MeV, Fermi_vals)

def E_function(Ee, Z, A, data):
    """
    Calculate the E function from Dirac radial wavefunctions.

    The function is computed from the product of the radial Dirac
    components g and f evaluated at the nuclear radius,

        E(Ee) = 2 g * f.

    Parameters
    ----------
    Ee : array_like
        Total relativistic electron energies in MeV.

    Z : int
        Atomic number.

    A : int
        Mass number.

    data : dict
        Dictionary containing the radial wavefunction data with keys:

        - "T" : kinetic energy mesh
        - "P_n" : upper radial wavefunction component
        - "Q_p" : lower radial wavefunction component
        - "idx_R" : index corresponding to the nuclear radius
        - "mesh_point_R_au" : nuclear radius mesh point in atomic units

    Returns
    -------
    ndarray
        Values of the E function evaluated at Ee.
    """
    s = np.sqrt(1-(ALPHA * Z)**2)

    T = Ee - ME
    T_mesh = data["T"]
    T_MeV = T_mesh * E_HARTREE/1e6

    g, f = calc_g_and_f(Ee, Z, A, data)
    E_vals = 2*g * f


    return np.interp(T, T_MeV, E_vals)


def Fermi(Ee, Z, A, rN):
    """
    Calculate the analytic pure Coulomb potential Fermi function.

    Parameters
    ----------
    Ee : ndarray
        Total relativistic energy values.
    Z : int
        Atomic number.
    A : int
        Mass number.
    rN : float
        Dimensionless nuclear radius R = 1.2 * A^(1/3) / HBAR_C

    Returns
    -------
    ndarray
        Values of analytic Fermi function for pure Coulomb potential up to second order correction

    """
    # Guard against Ee slightly below me due to numerical issues
    Ee = np.asarray(Ee)
    p2 = Ee**2 - ME**2
    # Set negative p2 to a tiny positive to avoid NaNs exactly at the threshold
    p2 = np.where(p2 > 0, p2, np.finfo(float).tiny)
    p = np.sqrt(p2)
    y = ALPHA * Z * Ee / p
    gamma0 = np.sqrt(1 - (ALPHA * Z)**2)
    F = (sp.gamma(3) / (sp.gamma(1) * sp.gamma(1 + 2 * gamma0)))**2
    F *= (2 * p * rN)**(2 * (gamma0 - 1)) * np.exp(np.pi * y)
    F *= np.abs(sp.gamma(gamma0 + 1j * y))**2

    firstorder_corr = 6 * p * rN * np.sqrt((1-gamma0)/(1+gamma0)) * (1+gamma0 - 2*gamma0* (p/Ee)**2/3)/((1+ 2*gamma0)*p/Ee)

    secondorder_corr = -(p * rN)**2 * (1-gamma0)/(1+gamma0) * (-2*(1+gamma0)* (5 + 4*gamma0) + (1 + 6*gamma0 + 4*gamma0**2)*(p/Ee)**2)/((1 + 2*gamma0) * p/Ee)**2

    return F #* (1 -firstorder_corr - secondorder_corr)


def plot_f_and_g(Ee, potential_index, cnf, data, output_directory_name):
    """
    Calculates and plots the numeric and analytic g and f Dirac wave function component for comparison

    Analytic g and f components are calculated via methods described in "Angular Distributions of Emitted Electrons in the Two-Neutrino
    ββ Decay" by Ovidiu. Note the Thomas-Fermi potential does not have an analytic solution

    Parameters
    ----------
    Ee : ndarray
        Total relativistic energy values
    potential_index: int
        Index specifying which potential model to use.
    cnf : dict
        Dictionary containing the isotope configurations
        - "Z" : Atomic number.
        - "A" : Mass number.
        - "Q" : MeV Q-value.
    data : dict
        Dictionary containing the radial wavefunction data with keys:

        - "T" : kinetic energy mesh
        - "P_n" : upper radial wavefunction component
        - "Q_p" : lower radial wavefunction component
        - "idx_R" : index corresponding to the nuclear radius
        - "mesh_point_R_au" : nuclear radius mesh point in atomic units
    output_directory_name : string
        Name of directory to which the plots are saved



    """
    Z = cnf["Z"] # Atomic number
    A = cnf["A"] # Atomic Mass number
    Q = cnf["Q"] # MeV Q-value
    rN = 1.2 * A ** (1 / 3) / HBAR_C # Nuclear radius

    scheme = None
    f_analytic = g_analytic = None

    g_numeric, f_numeric = calc_g_and_f(Ee, Z, A, data)

    g_fortran, E_fortran = Fortran_data()

    if potential_index == 0:
        scheme = "B"

        g_analytic = np.empty_like(Ee, dtype = float)
        f_analytic = np.empty_like(Ee, dtype = float)

        kappa_g = -1
        kappa_f = 1

        #### SIMOKVIC ANALYTIC FORMULA
        # for i , E in enumerate(Ee):
        #     p = np.sqrt(E**2 - ME**2)
        #     eta = ALPHA * Z* E/ p
        #     gammak = np.sqrt(1 - (ALPHA * Z)**2)

        #     numerator = np.abs(sp.gamma(1 + gammak + 1j * eta))
        #     denominator = sp.gamma(1 + 2 * gammak)
        #     gamma_ratio = numerator/denominator

        #     sqrt_term_plus = np.sqrt((E + ME) / (2 * E))
        #     sqrt_term_min = np.sqrt((E - ME) / (2 * E))

        #     exp_zeta_g = np.sqrt((kappa_g - 1j * eta * ME/E) / (gammak - 1j * eta))
        #     exp_zeta_f = np.sqrt((kappa_f - 1j * eta * ME/E) / (gammak - 1j * eta))


        #     hyp = complex(mp.hyp1f1(gammak - 1j*eta, 1 + 2*gammak, -2*1j*p*rN))
        #     phase = np.exp(1j*p*rN)
        #     Im_term = np.imag(phase * exp_zeta_g * hyp )
        #     Re_term = np.real(phase * exp_zeta_f * hyp)

        #     g_analytic[i] = np.sign(kappa_g) * 1.0/(p*rN) * sqrt_term_plus * gamma_ratio * (2*p*rN)**gammak * np.exp(np.pi * eta/2) * Im_term
        #     f_analytic[i] = np.sign(kappa_f) * 1.0/(p*rN) * sqrt_term_min * gamma_ratio * (2*p*rN)**gammak * np.exp(np.pi * eta/2) * Re_term

        #### SAAD ANALYTIC FORMULA
        _alpha = mp.mpf('1') / mp.mpf(str(C))
        _me = mp.mpf(str(ME))
        _Z = mp.mpf(str(Z)) 

        for i, E in enumerate(Ee):
            W = mp.mpf(E)
            p = mp.sqrt(W**2 - _me**2)
            eta = _alpha * _Z * W / p
            S = mp.sqrt(1 - (_alpha * _Z)**2) # kappa^2 hard coded to equal 1
            nu = mp.arg(_alpha * _Z * (W + _me) - mp.mpc(0, 1) * (kappa_g + S) * p)
            Ak = -1 * (mp.exp(-mp.pi * eta / 2) * mp.fabs(mp.gamma(S + mp.mpc(0, 1) * eta)) / mp.gamma(2 * S + 1) * (2 * p * rN)**S)
            Fk = ((S - mp.mpc(0, 1) * eta) * mp.exp(mp.mpc(0, -1) * p * rN + mp.mpc(0, 1) * nu) * mp.hyp1f1(S + 1 + mp.mpc(0, -1) * eta, 2 * S + 1, mp.mpc(0, 2) * p * rN))
            psi_val = Ak * Fk
            g_analytic[i] = float(mp.re(psi_val))
            f_analytic[i] = float(-(p / (W + _me)) * mp.im(psi_val))


    elif potential_index == 2:
        scheme = "A"
        g_analytic = np.sqrt(Fermi(Ee, Z, A, rN)) * np.sqrt((Ee + ME)/(2*Ee))
        f_analytic = np.sqrt(Fermi(Ee, Z, A, rN)) * np.sqrt((Ee - ME)/ (2*Ee))

    elif potential_index == 3:
        scheme = "C"



    else:
        raise RuntimeError("No proper potential index has been passed")


    plt.figure(figsize=(12,8))
    plt.plot(Ee-ME, g_analytic, lw=1.5, label = "g analytic")
    plt.xlabel(r"$T$ (MeV)")
    plt.ylabel(r"$g_{\kappa=-1}(R)$")
    plt.xlim((Ee-ME)[0], (Ee-ME)[-1])
    plt.xscale("log")
    plt.title(f"g wave func comparison, Scheme {scheme}")
    plt.legend()
    plt.grid(True)
    plt.show()

    plt.figure(figsize=(12,8))
    plt.plot(Ee-ME, f_analytic, lw=1.5, label = "f analytic")
    plt.xlabel(r"$T$ (MeV)")
    plt.ylabel(r"$f_{\kappa=1}(R)$")
    plt.xlim((Ee-ME)[0], (Ee-ME)[-1])
    plt.xscale("log")
    plt.title(f"f wave func comparison, Scheme {scheme}")
    plt.legend()
    plt.show()



    if f_analytic is not None:
        fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(12,8), sharex=True, gridspec_kw={"height_ratios": [3,1]})
        ax1.plot(Ee-ME, abs(f_numeric), lw=1.5, label = "f numeric")
        ax1.plot(Ee-ME, f_analytic, lw=1.5, label = "f analytic")
        ax1.set_ylabel(r"$f_{\kappa=1}(R)$")
        ax1.set_ylim(0, 4)
        ax1.set_title(f"f wave func comparison, Scheme {scheme}")
        ax1.legend()
        ax1.grid(True)
        
        percent_diff_f = 100.0 * (abs(f_numeric) - f_analytic) / f_analytic
        ax2.plot(Ee-ME, percent_diff_f, lw=1.5)
        ax2.set_xlabel(r"$T$ (MeV)")
        ax2.set_ylabel("% diff")
        ax2.grid(True)
        
        ax1.set_xscale("log")
        plt.tight_layout()
        plt.savefig(os.path.join(output_directory_name, f"f_comparison_scheme_{scheme}.png"), dpi = 300)
        plt.show()
    else:
        fig = plt.figure(figsize=(12,8))
        plt.plot(Ee-ME, abs(f_numeric), lw=1.5, label = "f numeric")
        plt.xlabel(r"$T$ (MeV)")
        plt.ylabel(r"$f_{\kappa=1}(R)$")
        plt.xlim((Ee-ME)[0], (Ee-ME)[-1])
        plt.xscale("log")
        plt.ylim(0, 4)
        plt.title(f"f wave func comparison, Scheme {scheme}")
        plt.legend()
        plt.grid(True)
        plt.savefig(os.path.join(output_directory_name, f"f_comparison_scheme_{scheme}.png"), dpi = 300)
        plt.show()


    if g_analytic is not None:
        fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(12,8), sharex=True, gridspec_kw={"height_ratios": [3,1]})
        ax1.plot(E_fortran, abs(g_fortran), lw=1.5, label = "g Fortran")
        ax1.plot(Ee-ME, abs(g_numeric), lw=1.5, label = "g numeric")
        ax1.plot(Ee-ME, g_analytic, lw=1.5, label = "g analytic")
        ax1.set_ylabel(r"$g_{\kappa=-1}(R)$")
        ax1.set_ylim(0, 20)
        ax1.set_title(f"g wave func comparison, Scheme {scheme}")
        ax1.legend()
        ax1.grid(True)
        
        percent_diff_g = 100.0 * (abs(g_numeric) - g_analytic) / g_analytic
        ax2.plot(Ee-ME, percent_diff_g, lw=1.5)
        ax2.set_xlabel(r"$T$ (MeV)")
        ax2.set_ylabel("% diff")
        ax2.grid(True)
        
        ax1.set_xscale("log")
        plt.tight_layout()
        plt.savefig(os.path.join(output_directory_name, f"g_comparison_scheme_{scheme}.png"), dpi = 300)
        plt.show()
    else:
        fig = plt.figure(figsize=(12,8))
        plt.plot(E_fortran, abs(g_fortran), lw=1.5, label = "g Fortran")
        plt.plot(Ee-ME, abs(g_numeric), lw=1.5, label = "g numeric")
        plt.xlabel(r"$T$ (MeV)")
        plt.ylabel(r"$g_{\kappa=-1}(R)$")
        plt.xlim((Ee-ME)[0], (Ee-ME)[-1])
        plt.xscale("log")
        plt.ylim(0, 20)
        plt.title(f"g wave func comparison, Scheme {scheme}")
        plt.legend()
        plt.grid(True)
        plt.savefig(os.path.join(output_directory_name, f"g_comparison_scheme_{scheme}.png"), dpi = 300)
        plt.show()

    return None
