#!/usr/bin/env python
from logging import config
from sys import prefix
from matplotlib.gridspec import GridSpec
import numpy as np
from scipy.integrate._ivp.radau import predict_factor
import scipy.special as sp
import matplotlib.pyplot as plt
from scipy.integrate import nquad
from scipy.integrate import quad
from scipy.interpolate import interp1d
from pathlib import Path
import mpmath as mp
import os
import glob, re
from configurations.physics_constants import ME, ALPHA, GF, VUD, HBAR_C, GA, AU, C, E_HARTREE
from algorithms.integrands import phase_space_integrand , spectrum_epsilon 

Gbeta = GF * VUD # Effective weak coupling constant in MeV^-2
c2n = ME * (Gbeta * ME ** 2)**4 / (8 * np.pi**7)
MeVtoyr = (365.25 * 24 * 3600) * 2.998e8 / (1e-15 * HBAR_C)
MGT1, MGT3, MGT5, xi31, xi51 = 0.0104, 0.00403, 0.00126, 0.3867, 0.1207 # Simkovic NMEs for 136Xe

#### FORTRAN DATA EXTRACTION

def Fortran_data():
    """
    Exctracts the output data generated by RADIAL FORTRAN subroutine, and calculates the g component for comparison

    This is probably a temporary function purely for comparing data.

    Results
    -------
    g_func : ndarray
        Calculated upper wave function component for kappa = -1
    E_values : ndarray
        The total relativistic energies on which g_func was evaluated
    """
    directory = "out_fortran"
    P_values = []
    E_values = []

    pattern = os.path.join(directory, "cxem_*.out")
    R_value_fortran = None

    for filename in sorted(glob.glob(pattern)):
        E = None
        with open(filename, "r") as f:
            for line in f:
                if "Free state:" in line:
                    match = re.search(r"E=\s*([+-]?\d+\.\d+E[+-]\d+)", line)

                    if match:
                        E = float(match.group(1))

                parts = line.split()

                # Skip header/non-data lines
                if len(parts) != 3:
                    continue

                try:
                    R = float(parts[0])
                    P = float(parts[1])

                    # First nonzero R
                    if R != 0.0:
                        if R_value_fortran is None:
                            R_value_fortran = R
                        P_values.append(P)
                        E_values.append(E)
                        break

                except ValueError:
                    continue
    if R_value_fortran is None:
        raise RuntimeError("No matching radius extracted")

    P_values = np.array(P_values)
    E_values = np.array(E_values) * E_HARTREE/1e6

    print(f"R = {R_value_fortran}")
    print(f"R in a.u = {R_value_fortran/ AU}")
    print(f"E values = {E_values}")
    print(f"P(R) values = {P_values}")



    p = np.sqrt(E_values * (E_values + 2*C**2))/C
    total_E = E_values + ME
    g_func = np.sqrt((total_E + ME)/(2*total_E)) * P_values /(p * R_value_fortran/AU)

    plt.figure(figsize=(12,8))
    plt.plot(E_values, g_func)
    plt.xscale("log")
    plt.show()

    return g_func, E_values



def load_data(directory_name, file_name):
    """
    Extracts Energy T, radial grid r, upper component wave function P and lower component
    wave function Q from the given .npz file.

    Parameters
    ----------
    directory_name : string
        Name of the directory in which .npz file is located.
    file_name : string
        Name of the .npz file

    Returns
    -------
    T : list
        List of kinetic energy values for which P and Q where evaluated
    r : list
        Radial grid points on which P and Q are calculated
    P : list
        List of upper component of Dirac wave function for each T on radial grid r
    Q : list
        List of lower component of Dirac wave function for each T on radial grid r
    """
    full_path = Path(directory_name)/ file_name
    data = np.load(full_path)

    print(f"loading file from {full_path}")

    T = data["T"]
    r = data["r"]
    P = data["P"]
    Q = data["Q"]
    return T, r, P, Q



def find_mesh_point_R_au(grid_points, rN):
    """
    Obtains the index and value of r_grid which match the nuclear radius or come closest to it.

    Parameters
    ----------
    grid_points : ndarray
        One dimensional ndarray of the radial grid
    rN : float
        Dimensionless nuclear radius defined as R = 1.2 * A^(1/3) / HBAR_C

    Returns
    -------
    idx_R : int
        Index point at which grid_points matches nuclear radius or comes closest to it
    grid_point_R_au : float
        Value of grid_points which matches the nuclear radius or comes closest to it
    """
    R_au = rN * HBAR_C * 1e-15 /AU
    idx_R = 0
    grid_point_R_au = 0
    for i in range(0,len(grid_points)-1):
        if grid_points[i] <= R_au  and grid_points[i+1] > R_au:
            grid_point_R_au = grid_points[i]
            idx_R = i
            print(f"closest mesh point to R_au = {R_au: .5g} is at i ={idx_R} w/ mesh point value ={grid_point_R_au: .5g}")
            break
    return idx_R, grid_point_R_au


def calc_g_and_f(Ee, Z, A, data):
    """
    Calculate the radial Dirac wavefunction components g with kappa = -1 and f with kappa = +1.

    The functions are computed from the radial wavefunction components
    P and Q following the conventions used in
    "Angular Distributions of Emitted Electrons in the Two-Neutrino
    ββ Decay" by Ovidiu.

    Parameters
    ----------
    Ee : ndarray
        Total relativsitc energy values.
    Z : int
        Atomic number.
    A : int
        Mass number.
    data : dict
        Dictionary containing the radial wavefunction data with keys:

        - "T" : kinetic energy mesh
        - "P_n" : upper radial wavefunction component
        - "Q_p" : lower radial wavefunction component
        - "idx_R" : index corresponding to the nuclear radius
        - "mesh_point_R_au" : nuclear radius mesh point in atomic units

    Returns
    -------
    g_n1 : ndarray
        Upper component of dirac wavefunction for kappa = -1
    f_p1 : ndarray
        Lower component of dirac wavefunction for kappa = +1
    """
    Ee = np.asarray(Ee, dtype = float)

    T_mesh = data["T"]
    P_n = data["P_n"]
    Q_p = data["Q_p"]
    idx_R = data["idx_R"]
    mesh_point_R_au = data["mesh_point_R_au"]


    T_MeV = T_mesh * E_HARTREE/1e6
    Ee = T_MeV + ME
    p_au = np.sqrt(T_mesh * (T_mesh + 2*C**2))/C


    g_n1 = np.sqrt((Ee + ME)/(2*Ee)) * P_n[:,idx_R] /(p_au * mesh_point_R_au)
    f_p1 = np.sqrt((Ee + ME)/(2*Ee)) * Q_p[:,idx_R] / (p_au * mesh_point_R_au)

    return g_n1, f_p1



def Fermi_numerical(Ee, Z, A, data):
    """
    Calculate the numerical Fermi function from Dirac radial wavefunctions.

    The Fermi function is computed from the radial Dirac components
    g and f evaluated at the nuclear radius,

        F(Z, Ee) = 2 * (g^2 + f^2) / (s + 1)

    where

        s = sqrt(1 - (Z / A)^2).

    Parameters
    ----------
    Ee : array_like
        Total relativistic electron energies in MeV.

    Z : int
        Atomic number.

    A : int
        Mass number.

    data : dict
        Dictionary containing the radial wavefunction data with keys:

        - "T" : kinetic energy mesh
        - "P_n" : upper radial wavefunction component
        - "Q_p" : lower radial wavefunction component
        - "idx_R" : index corresponding to the nuclear radius
        - "mesh_point_R_au" : nuclear radius mesh point in atomic units

    Returns
    -------
    ndarray
        Numerical Fermi function evaluated at Ee.
    """
    s = np.sqrt(1-(Z/A)**2)

    T = Ee - ME
    T_mesh = data["T"]
    T_MeV = T_mesh * E_HARTREE/1e6

    g, f = calc_g_and_f(Ee, Z, A, data)


    Fermi_vals = (g**2 + f**2)

    return 2/(s+1) * np.interp(T, T_MeV, Fermi_vals)

def E_function(Ee, Z, A, data):
    """
    Calculate the E function from Dirac radial wavefunctions.

    The function is computed from the product of the radial Dirac
    components g and f evaluated at the nuclear radius,

        E(Ee) = 2 g * f.

    Parameters
    ----------
    Ee : array_like
        Total relativistic electron energies in MeV.

    Z : int
        Atomic number.

    A : int
        Mass number.

    data : dict
        Dictionary containing the radial wavefunction data with keys:

        - "T" : kinetic energy mesh
        - "P_n" : upper radial wavefunction component
        - "Q_p" : lower radial wavefunction component
        - "idx_R" : index corresponding to the nuclear radius
        - "mesh_point_R_au" : nuclear radius mesh point in atomic units

    Returns
    -------
    ndarray
        Values of the E function evaluated at Ee.
    """
    s = np.sqrt(1-(Z/A)**2)

    T = Ee - ME
    T_mesh = data["T"]
    T_MeV = T_mesh * E_HARTREE/1e6

    g, f = calc_g_and_f(Ee, Z, A, data)
    E_vals = 2*g * f


    return np.interp(T, T_MeV, E_vals)


def Fermi(Ee, Z, A, rN):
    """
    Calculate the analytic pure Coulomb potential Fermi function.

    Parameters
    ----------
    Ee : ndarray
        Total relativistic energy values.
    Z : int
        Atomic number.
    A : int
        Mass number.
    rN : float
        Dimensionless nuclear radius R = 1.2 * A^(1/3) / HBAR_C

    Returns
    -------
    ndarray
        Values of analytic Fermi function for pure Coulomb potential up to second order correction

    """
    # Guard against Ee slightly below me due to numerical issues
    Ee = np.asarray(Ee)
    p2 = Ee**2 - ME**2
    # Set negative p2 to a tiny positive to avoid NaNs exactly at the threshold
    p2 = np.where(p2 > 0, p2, np.finfo(float).tiny)
    p = np.sqrt(p2)
    y = ALPHA * Z * Ee / p
    gamma0 = np.sqrt(1 - (ALPHA * Z)**2)
    F = (sp.gamma(3) / (sp.gamma(1) * sp.gamma(1 + 2 * gamma0)))**2
    F *= (2 * p * rN)**(2 * (gamma0 - 1)) * np.exp(np.pi * y)
    F *= np.abs(sp.gamma(gamma0 + 1j * y))**2

    firstorder_corr = 6 * p * rN * np.sqrt((1-gamma0)/(1+gamma0)) * (1+gamma0 - 2*gamma0* (p/Ee)**2/3)/((1+ 2*gamma0)*p/Ee)

    secondorder_corr = -(p * rN)**2 * (1-gamma0)/(1+gamma0) * (-2*(1+gamma0)* (5 + 4*gamma0) + (1 + 6*gamma0 + 4*gamma0**2)*(p/Ee)**2)/((1 + 2*gamma0) * p/Ee)**2

    return F# * (1 -firstorder_corr - secondorder_corr)


def plot_f_and_g(Ee, potential_index, cnf, data, output_directory_name):
    """
    Calculates and plots the numeric and analytic g and f Dirac wave function component for comparison

    Analytic g and f components are calculated via methods described in "Angular Distributions of Emitted Electrons in the Two-Neutrino
    ββ Decay" by Ovidiu. Note the Thomas-Fermi potential does not have an analytic solution

    Parameters
    ----------
    Ee : ndarray
        Total relativistic energy values
    potential_index: int
        Index specifying which potential model to use.
    cnf : dict
        Dictionary containing the isotope configurations
        - "Z" : Atomic number.
        - "A" : Mass number.
        - "Q" : MeV Q-value.
    data : dict
        Dictionary containing the radial wavefunction data with keys:

        - "T" : kinetic energy mesh
        - "P_n" : upper radial wavefunction component
        - "Q_p" : lower radial wavefunction component
        - "idx_R" : index corresponding to the nuclear radius
        - "mesh_point_R_au" : nuclear radius mesh point in atomic units
    output_directory_name : string
        Name of directory to which the plots are saved



    """
    Z = cnf["Z"] # Atomic number
    A = cnf["A"] # Atomic Mass number
    Q = cnf["Q"] # MeV Q-value
    rN = 1.2 * A ** (1 / 3) / HBAR_C # Nuclear radius

    scheme = None
    f_analytic = g_analytic = None

    g_numeric, f_numeric = calc_g_and_f(Ee, Z, A, data)

    g_fortran, E_fortran = Fortran_data()

    if potential_index == 0:
        scheme = "B"

        out_g = np.empty_like(Ee, dtype = float)
        out_f = np.empty_like(Ee, dtype = float)

        kappa_g = -1
        kappa_f = 1


        for i , E in enumerate(Ee):
            p = np.sqrt(E**2 - ME**2)
            eta = ALPHA * Z* E/ p
            gammak = np.sqrt(1 - (ALPHA * Z)**2)

            numerator = np.abs(sp.gamma(1 + gammak + 1j * eta))
            denominator = sp.gamma(1 + 2 * gammak)
            gamma_ratio = numerator/denominator

            sqrt_term_plus = np.sqrt((E + ME) / (2 * E))
            sqrt_term_min = np.sqrt((E - ME) / (2 * E))

            exp_zeta_g = np.sqrt((kappa_g - 1j * eta * ME/E) / (gammak - 1j * eta))
            exp_zeta_f = np.sqrt((kappa_f - 1j * eta * ME/E) / (gammak - 1j * eta))


            hyp = mp.hyp1f1(gammak - 1j*eta, 1 + 2*gammak, -2*1j*p*rN)
            Im_term = np.imag(np.exp(1j*p*rN) * exp_zeta_g * hyp )
            Re_term = np.real(np.exp(1j*p*rN) * exp_zeta_f * hyp)

            out_g[i] = np.sign(kappa_g) * 1.0/(p*rN) * sqrt_term_plus * gamma_ratio * (2*p*rN)**gammak * np.exp(np.pi * eta/2) * Im_term
            out_f[i] = np.sign(kappa_f) * 1.0/(p*rN) * sqrt_term_min * gamma_ratio * (2*p*rN)**gammak * np.exp(np.pi * eta/2) * Re_term

        g_analytic = out_g
        f_analytic = out_f
    elif potential_index == 2:
        scheme = "A"
        g_analytic = np.sqrt(Fermi(Ee, Z, A, rN)) * np.sqrt((Ee + ME)/(2*Ee))
        f_analytic = np.sqrt(Fermi(Ee, Z, A, rN)) * np.sqrt((Ee - ME)/ (2*Ee))

    elif potential_index == 3:
        scheme = "C"



    else:
        raise RuntimeError("No proper potential index has been passed")





    if f_analytic is not None:
        fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(12,8), sharex=True, gridspec_kw={"height_ratios": [3,1]})
        ax1.plot(Ee-ME, abs(f_numeric), lw=1.5, label = "f numeric")
        ax1.plot(Ee-ME, f_analytic, lw=1.5, label = "f analytic")
        ax1.set_ylabel(r"$f_{\kappa=1}(R)$")
        ax1.set_ylim(0, 4)
        ax1.set_title(f"f wave func comparison, Scheme {scheme}")
        ax1.legend()
        ax1.grid(True)
        
        percent_diff_f = 100.0 * (abs(f_numeric) - f_analytic) / f_analytic
        ax2.plot(Ee-ME, percent_diff_f, lw=1.5)
        ax2.set_xlabel(r"$T$ (MeV)")
        ax2.set_ylabel("% diff")
        ax2.grid(True)
        
        ax1.set_xscale("log")
        plt.tight_layout()
        plt.savefig(os.path.join(output_directory_name, f"f_comparison_scheme_{scheme}.png"), dpi = 300)
        plt.show()
    else:
        fig = plt.figure(figsize=(12,8))
        plt.plot(Ee-ME, abs(f_numeric), lw=1.5, label = "f numeric")
        plt.xlabel(r"$T$ (MeV)")
        plt.ylabel(r"$f_{\kappa=1}(R)$")
        plt.xlim((Ee-ME)[0], (Ee-ME)[-1])
        plt.xscale("log")
        plt.ylim(0, 4)
        plt.title(f"f wave func comparison, Scheme {scheme}")
        plt.legend()
        plt.grid(True)
        plt.savefig(os.path.join(output_directory_name, f"f_comparison_scheme_{scheme}.png"), dpi = 300)
        plt.show()


    if g_analytic is not None:
        fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(12,8), sharex=True, gridspec_kw={"height_ratios": [3,1]})
        ax1.plot(E_fortran, abs(g_fortran), lw=1.5, label = "g Fortran")
        ax1.plot(Ee-ME, abs(g_numeric), lw=1.5, label = "g numeric")
        ax1.plot(Ee-ME, g_analytic, lw=1.5, label = "g analytic")
        ax1.set_ylabel(r"$g_{\kappa=-1}(R)$")
        ax1.set_ylim(0, 20)
        ax1.set_title(f"g wave func comparison, Scheme {scheme}")
        ax1.legend()
        ax1.grid(True)
        
        percent_diff_g = 100.0 * (abs(g_numeric) - g_analytic) / g_analytic
        ax2.plot(Ee-ME, percent_diff_g, lw=1.5)
        ax2.set_xlabel(r"$T$ (MeV)")
        ax2.set_ylabel("% diff")
        ax2.grid(True)
        
        ax1.set_xscale("log")
        plt.tight_layout()
        plt.savefig(os.path.join(output_directory_name, f"g_comparison_scheme_{scheme}.png"), dpi = 300)
        plt.show()
    else:
        fig = plt.figure(figsize=(12,8))
        plt.plot(E_fortran, abs(g_fortran), lw=1.5, label = "g Fortran")
        plt.plot(Ee-ME, abs(g_numeric), lw=1.5, label = "g numeric")
        plt.xlabel(r"$T$ (MeV)")
        plt.ylabel(r"$g_{\kappa=-1}(R)$")
        plt.xlim((Ee-ME)[0], (Ee-ME)[-1])
        plt.xscale("log")
        plt.ylim(0, 20)
        plt.title(f"g wave func comparison, Scheme {scheme}")
        plt.legend()
        plt.grid(True)
        plt.savefig(os.path.join(output_directory_name, f"g_comparison_scheme_{scheme}.png"), dpi = 300)
        plt.show()

    return None




# ========== PHASE-SPACE FACTORS CALCULATION ==========

def calculate_phase_space_factors(Q, Fermi_analytic, Fermi_numeric, E_numeric):
    """
    Calculate phase-space factors G and H for double beta decay.

    Parameters
    ----------
    Q : float
        Q-value of the decay process.
    Fermi_analytic : callable
        Analytic Fermi function.
    Fermi_numeric : callable
        Numerical Fermi function from Dirac solutions.
    E_numeric : callable
        Numerical E function.

    Returns
    -------
    dict
        Dictionary containing G_results, G_errors, G_results_num, G_errors_num, H_results_num, H_errors_num
    """
    def bounds_Ee1():
        return [ME, Q + ME]
    
    def bounds_Ee2(Ee1):
        return [ME, Q + 2.0 * ME - Ee1]

    opts_Ee1 = {"epsabs": 1e-18, "epsrel": 1e-16, "limit": 50000, "points": [ME, Q/2 + ME, Q + ME]}
    opts_Ee2 = {"epsabs": 1e-18, "epsrel": 1e-16, "limit": 50000, "points": [ME]}

    tags = [0, 2, 4, 22]
    G_results_list, G_errors_list = [], []
    G_results_num_list, G_errors_num_list = [], []
    H_results_num_list, H_errors_num_list = [], []
    
    for t in tags:
        # Analytic G values
        G_output = nquad(phase_space_integrand(t, Q, Fermi_analytic), [bounds_Ee2, bounds_Ee1], opts=[opts_Ee2, opts_Ee1])
        G_result, G_error = G_output[:2]
        G_results_list.append(G_result)
        G_errors_list.append(G_error)

        # Numeric G values
        G_output_num = nquad(phase_space_integrand(t, Q, Fermi_numeric), [bounds_Ee2, bounds_Ee1], opts=[opts_Ee2, opts_Ee1])
        G_result_num, G_error_num = G_output_num[:2]
        G_results_num_list.append(G_result_num)
        G_errors_num_list.append(G_error_num)

        # H values (numeric only)
        H_output_num = nquad(phase_space_integrand(t, Q, E_numeric), [bounds_Ee2, bounds_Ee1], opts=[opts_Ee2, opts_Ee1])
        H_result, H_error = H_output_num[:2]
        H_results_num_list.append(H_result)
        H_errors_num_list.append(H_error)

    return {
        "G_results": np.asarray(G_results_list),
        "G_errors": np.asarray(G_errors_list),
        "G_results_num": np.asarray(G_results_num_list),
        "G_errors_num": np.asarray(G_errors_num_list),
        "H_results_num": np.asarray(H_results_num_list),
        "H_errors_num": np.asarray(H_errors_num_list),
    }


# ========== FERMI FUNCTION PLOTTING ==========

def plot_fermi_function(Q, Z, A, rN, data, plots_output_directory, potential_index):
    """
    Plot analytical vs numerical Fermi functions.

    Parameters
    ----------
    Q : float
        Q-value of the decay process.
    Z : int
        Atomic number.
    A : int
        Mass number.
    rN : float
        Nuclear radius (dimensionless).
    data : dict
        Wavefunction data dictionary.
    plots_output_directory : str or Path
        Directory to save plots.
    potential_index : int
        Index specifying which potential model is used.
    """
    x_plot = np.linspace(ME + 1e-3, Q + ME, 2000)
    Analytic_fermi_plot = Fermi(x_plot, Z, A, rN)
    Numeric_fermi_plot = Fermi_numerical(x_plot, Z, A, data)

    fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(12, 8), sharex=True, gridspec_kw={"height_ratios": [3, 1]})
    
    # Top plot: comparison
    ax1.plot(x_plot, Analytic_fermi_plot, lw=1.5, label='Pure Coulomb Analytic')
    ax1.plot(x_plot, Numeric_fermi_plot, lw=1.5, label='Numerical')
    ax1.set_ylabel('Fermi Function Value')
    ax1.set_title('Fermi Function vs Electron Energy')
    ax1.grid(True)
    ax1.legend()

    # Bottom plot: percentage difference
    percent_diff_fermi = 100.0 * (Numeric_fermi_plot - Analytic_fermi_plot) / Analytic_fermi_plot
    ax2.plot(x_plot, percent_diff_fermi, lw=1.5)
    ax2.set_xlabel('Electron Energy (MeV)')
    ax2.set_ylabel('% Difference')
    ax2.grid(True)

    plt.tight_layout()
    plt.savefig(os.path.join(plots_output_directory, f"Fermi_Function_potential_{potential_index}_Z{Z}_A{A}.png"), dpi=300)
    plt.show()


# ========== SPECTRUM CALCULATION AND PLOTTING ==========

def calculate_and_plot_spectra(Q, Z, A, Fermi_analytic, Fermi_numeric, plots_output_directory, potential_index):
    """
    Calculate and plot 2νββ epsilon spectrum.

    Parameters
    ----------
    Q : float
        Q-value of the decay process.
    Z : int
        Atomic number.
    A : int
        Mass number.
    Fermi_analytic : callable
        Analytic Fermi function.
    Fermi_numeric : callable
        Numerical Fermi function.
    plots_output_directory : str or Path
        Directory to save plots.
    potential_index : int
        Index specifying which potential model is used.

    Returns
    -------
    dict
        Dictionary containing spectrum data and rates
    """
    eps_grid = np.linspace(0.0, Q, 400)
    spectrum_vals = np.array([spectrum_epsilon(eps, Q, Fermi_analytic) for eps in eps_grid])
    spectrum_vals_num = np.array([spectrum_epsilon(eps, Q, Fermi_numeric) for eps in eps_grid])

    # ========== Plot differential spectrum ==========
    fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(12, 8), sharex=True, gridspec_kw={"height_ratios": [3, 1]})
    
    ax1.plot(eps_grid, spectrum_vals, lw=1.5, label="Pure Coulomb Analytic")
    ax1.plot(eps_grid, spectrum_vals_num, lw=1.5, label="Numerical")
    ax1.set_ylabel('dΓ/dε (1/yr per MeV)')
    ax1.set_title('2νββ Spectrum vs epsilon')
    ax1.legend()
    ax1.grid(True)

    percent_diff_eps = 100.0 * (spectrum_vals_num - spectrum_vals) / spectrum_vals
    ax2.plot(eps_grid, percent_diff_eps, lw=1.5)
    ax2.set_xlabel('epsilon = Ee1 + Ee2 − 2 me (MeV)')
    ax2.set_ylabel('% Difference')
    ax2.grid(True)

    plt.tight_layout()
    plt.savefig(os.path.join(plots_output_directory, f"Spectrum_potential_{potential_index}_Z{Z}_A{A}.png"), dpi=300)
    plt.show()

    # ========== Calculate total rates ==========
    total_rate, total_err = quad(lambda eps: spectrum_epsilon(eps, Q, Fermi_analytic), 0.0, Q,
                                 epsabs=1e-18, epsrel=1e-16, limit=20000, points=[0.0, Q/2.0, Q])
    total_rate_num, total_err_num = quad(lambda eps: spectrum_epsilon(eps, Q, Fermi_numeric), 0.0, Q,
                                         epsabs=1e-18, epsrel=1e-16, limit=20000, points=[0.0, Q/2.0, Q])

    # ========== Plot normalized spectrum ==========
    spec_vals_norm = spectrum_vals / total_rate
    spec_vals_norm_num = spectrum_vals_num / total_rate_num

    plt.figure(figsize=(12, 8))
    plt.plot(eps_grid, spec_vals_norm, lw=1.5, label="Analytic")
    plt.plot(eps_grid, spec_vals_norm_num, lw=1.5, label="Numeric")
    plt.xlabel('epsilon = Ee1 + Ee2 − 2 me (MeV)')
    plt.ylabel('1/Γ dΓ/dε')
    plt.title("Normalized 2νββ Spectrum")
    plt.legend()
    plt.grid(True)
    plt.show()

    norm_check = np.trapezoid(spec_vals_norm, eps_grid)
    norm_check_num = np.trapezoid(spec_vals_norm_num, eps_grid)
    print(f"Normalization check - Analytic: {norm_check:.10g}, Numeric: {norm_check_num:.10g}")

    return {
        "eps_grid": eps_grid,
        "spectrum_vals": spectrum_vals,
        "spectrum_vals_num": spectrum_vals_num,
        "total_rate": total_rate,
        "total_rate_num": total_rate_num,
        "total_err": total_err,
        "total_err_num": total_err_num,
    }


# ========== RESULTS OUTPUT ==========

def write_results_to_file(results_output_path, config, potential_index, Z, A, G_results, G_results_num, 
                          H_results_num, halflife, halflife_num, total_rate, total_rate_num, 
                          total_err, total_err_num, cnf):
    """
    Write phase-space factors and half-lives to output file.

    Parameters
    ----------
    results_output_path : str or Path
        Path to output file.
    config : dict
        Configuration dictionary.
    potential_index : int
        Potential model index.
    Z, A : int
        Atomic and mass numbers.
    G_results, G_results_num : ndarray
        Analytic and numeric G factors.
    H_results_num : ndarray
        Numeric H factors.
    halflife, halflife_num : float
        Analytic and numeric half-lives.
    total_rate, total_rate_num : float
        Total decay rates.
    total_err, total_err_num : float
        Integration errors.
    cnf : dict
        Isotope configuration dictionary.
    """
    # Determine scheme
    scheme_map = {0: "B", 2: "A", 3: "C"}
    scheme = scheme_map.get(potential_index, "Unknown")

    Simkovic_Gs = cnf.get("Simkovic_Gs", None)
    Simkovic_Hs = cnf.get("Simkovic_Hs", None)

    with open(results_output_path, "w") as f:
        f.write(f"### Double Beta Decay Results for {config['isotope']} using Scheme {scheme} ###\n\n")
        
        # ========== G factors ==========
        f.write("G FACTORS (Phase-Space)\n")
        f.write(f"{'Tags':<10} {'Analytic':<15} {'Numeric':<15} {'% Difference':<15}\n")
        f.write("-" * 55 + "\n")
        
        tags = ["G0", "G2", "G4", "G22"]
        for i, tag in enumerate(tags):
            if Simkovic_Gs is not None:
                percent_diff = 100.0 * (G_results_num[i] - Simkovic_Gs[i]) / Simkovic_Gs[i]
            else:
                percent_diff = 100.0 * (G_results_num[i] - G_results[i]) / G_results[i]
            f.write(f"{tag:<10} {G_results[i]:<15.6e} {G_results_num[i]:<15.6e} {percent_diff:<15.6f}\n")
        
        if Simkovic_Gs is not None:
            f.write(f"\nSimkovic Reference: {Simkovic_Gs}\n")
        f.write("\n")

        # ========== H factors ==========
        if Simkovic_Hs is not None:
            f.write("H FACTORS\n")
            f.write(f"{'Tags':<10} {'Numeric':<15} {'Simkovic':<15} {'% Difference':<15}\n")
            f.write("-" * 55 + "\n")
            for i, tag in enumerate(tags):
                percent_diff = 100.0 * (H_results_num[i] - Simkovic_Hs[i]) / Simkovic_Hs[i]
                f.write(f"{tag:<10} {H_results_num[i]:<15.6e} {Simkovic_Hs[i]:<15.6e} {percent_diff:<15.6f}\n")
            f.write("\n")

        # ========== Half-lives ==========
        f.write("HALF-LIVES\n")
        f.write("-" * 40 + "\n")
        f.write(f"Calculated (Analytic):  {halflife:.6e} yr\n")
        f.write(f"Calculated (Numeric):   {halflife_num:.6e} yr\n")
        f.write(f"Experimental:           {2.19e21:.6e} yr\n\n")

        # ========== Decay rates ==========
        f.write("DECAY RATES FROM ε-SPECTRUM\n")
        f.write("-" * 40 + "\n")
        f.write(f"Analytic:  {1/total_rate:.6e} ± {total_err:.6e} yr\n")
        f.write(f"Numeric:   {1/total_rate_num:.6e} ± {total_err_num:.6e} yr\n")


# ========== MAIN SPECTRUM CALCULATION ==========

def calc_double_beta_decay_spectrum(config, cnf):
    """
    Compute phase-space factors, half-lives, and energy spectra for
    two-neutrino double beta decay (2νββ).

    Orchestrates the calculation pipeline:
    1. Load wavefunction data from NPZ files
    2. Plot f, g, and Fermi functions
    3. Calculate phase-space factors (G and H)
    4. Calculate and plot spectra
    5. Write results to file

    Parameters
    ----------
    config : dict
        Main configuration dictionary
    cnf : dict
        Isotope configuration dictionary with Z, A, Q values
    """
    # ========== SETUP ==========
    Z = cnf["Z"]
    A = cnf["A"]
    Q = cnf["Q"]
    rN = 1.2 * A ** (1 / 3) / HBAR_C
    potential_index = config["generator"]["potential_index"]

    # ========== DIRECTORIES ==========
    main_output_directory = Path(config["paths"]["output_directory"]) / f"Dirac_{config['isotope']}"
    directory_name = main_output_directory / "NPZ_files"
    plots_output_directory = main_output_directory / "plots"
    plots_output_directory.mkdir(parents=True, exist_ok=True)

    results_output_directory = main_output_directory / "phase_space_results"
    results_output_directory.mkdir(parents=True, exist_ok=True)
    results_output_path = results_output_directory / f"results_potential_{potential_index}_Z{Z}_A{A}.txt"

    # ========== LOAD DATA ==========
    file_name_kappa_n = f"{config['isotope']}_potential_{potential_index}_kappa_-1_Z{Z}_A{A}.npz"
    file_name_kappa_p = f"{config['isotope']}_potential_{potential_index}_kappa_+1_Z{Z}_A{A}.npz"

    T_n, r_n, P_n, Q_n = load_data(directory_name, file_name_kappa_n)
    T_p, r_p, P_p, Q_p = load_data(directory_name, file_name_kappa_p)

    idx_R, mesh_point_R_au = find_mesh_point_R_au(r_n, rN)
    data = {"T": T_n, "P_n": P_n, "Q_p": Q_p, "idx_R": idx_R, "mesh_point_R_au": mesh_point_R_au}

    T_MeV = T_n * E_HARTREE / 1e6
    Ee = T_MeV + ME

    # ========== PLOT WAVEFUNCTION COMPARISONS ==========
    plot_f_and_g(Ee, potential_index, cnf, data, plots_output_directory)

    # ========== PLOT FERMI FUNCTION ==========
    plot_fermi_function(Q, Z, A, rN, data, plots_output_directory, potential_index)

    # ========== SETUP FERMI FUNCTIONS ==========
    Fermi_analytic = lambda Ee: Fermi(Ee, Z, A, rN)
    Fermi_numeric = lambda Ee: Fermi_numerical(Ee, Z, A, data)
    E_numeric = lambda Ee: E_function(Ee, Z, A, data)

    # ========== CALCULATE PHASE-SPACE FACTORS ==========
    phase_space_data = calculate_phase_space_factors(Q, Fermi_analytic, Fermi_numeric, E_numeric)
    G_results = phase_space_data["G_results"]
    G_results_num = phase_space_data["G_results_num"]
    H_results_num = phase_space_data["H_results_num"]

    # ========== CALCULATE HALF-LIVES ==========
    halflife = 1 / (GA ** 4 * MGT1 ** 2 * (G_results[0] + xi31 * G_results[1] + 
                    1/3 * xi31 ** 2 * G_results[3] + (1/3 * xi31 ** 2 + xi51) * G_results[2]))
    
    halflife_num = 1 / (GA ** 4 * MGT1 ** 2 * (G_results_num[0] + xi31 * G_results_num[1] + 
                        1/3 * xi31 ** 2 * G_results_num[3] + (1/3 * xi31 ** 2 + xi51) * G_results_num[2]))

    # ========== CALCULATE AND PLOT SPECTRA ==========
    spectrum_data = calculate_and_plot_spectra(Q, Z, A, Fermi_analytic, Fermi_numeric, 
                                               plots_output_directory, potential_index)

    # ========== WRITE RESULTS ==========
    write_results_to_file(results_output_path, config, potential_index, Z, A, G_results, G_results_num,
                         H_results_num, halflife, halflife_num, spectrum_data["total_rate"],
                         spectrum_data["total_rate_num"], spectrum_data["total_err"],
                         spectrum_data["total_err_num"], cnf)
    
    print(f"\nResults written to: {results_output_path}")



